import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { evaluateSharedAgentContract, parseMdPipelineEdges, validatePipelineSubset, validateRosterAlignment } from "../scripts/validate-shared-agent-contract.mjs";
const contract = JSON.parse(readFileSync(new URL("../nucleus/agents/shared-nucleus-agents.json", import.meta.url), "utf8"));
const markdown = readFileSync(new URL("../nucleus/agents/shared-nucleus-agents.md", import.meta.url), "utf8");
test("shared agent contract validator passes for checked-in canonical MD and JSON", () => { const result = evaluateSharedAgentContract({ contract, markdown }); assert.deepEqual(result.failures, [], result.failures.join("\n")); assert.equal(result.checks, 6); });
test("shared agent contract validator fails when roster modes diverge", () => { const diverged = structuredClone(contract); diverged.agents = diverged.agents.map((agent) => agent.name === "blueprint" ? { ...agent, modes: ["implement"] } : agent); assert.ok(validateRosterAlignment(markdown, diverged).some((f) => f.includes("roster modes mismatch for blueprint"))); });
test("shared agent contract validator fails when pipeline DAG claims a non-delegation edge", () => { const divergedMarkdown = markdown.replace("blueprint -> belt", "blueprint -> roboports"); assert.ok(validatePipelineSubset(divergedMarkdown, contract).some((f) => f.includes("pipeline DAG edge blueprint->roboports"))); });
test("shared agent contract validator fails when execution context is missing from JSON", () => { const diverged = structuredClone(contract); delete diverged.packetContract; assert.ok(evaluateSharedAgentContract({ contract: diverged, markdown }).failures.some((f) => f.includes("execution context must exist"))); });
test("pipeline edge parser expands brace groups and strips parenthetical notes", () => { assert.deepEqual(parseMdPipelineEdges("```text\nroboports -> { biters (lens fanout), lab (lens fanout) }\nrepair-pack -> lab\n```"), [["roboports","biters"],["roboports","lab"],["repair-pack","lab"]]); });
